# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Village 2036
email: implication@village2036.org
description: >- # this means to ignore newlines until "baseurl:"
  Village 2036, la passion des donneés!
  Une communauté collaborative pour comprendre et expliquer les données ouvertes et publiques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/logos/workinprogressmap.png


# Build settings
theme: alembic-jekyll-theme
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

paginate: 10
paginate_path: blog/page:num

sass:
  style: compressed
permalink: pretty
excerp_separator: <!-- more -->
timezone: America/New_York


navigation_header:
  - title: Village 2036
    url: /
  - title: Enquêtes
    url: /enquetes/
  - title: À propos
    url: /apropos/

navigation_footer:
  - title: La passion des données! 
    url: https://github.com/village2036

collections:
  posts:
    title: "Enquêtes"
    output: true
    descriptions: Découvrez nos trouvailles
    feature_image: "/assets/preview1.png"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
